Scientist = input("Enter scientist's name: ")
discovery_year = int(input("Enter discovery year: "))
creature_name = input("Enter creature's name: ")
home_planet = input("Enter discovered planet:")
diet = input("Enter creature's diet:")

print(f"\n{'='*40}")
print("     XENO-BIOLOGY FIELD REPORT")
print(f"{'='*40}")
print()
print(f"Scientist:      Dr. {Scientist}")
print(f"Discovery Year: {discovery_year}")
print()
print(f"{'-'*40}")
print(f"Creature Name: {creature_name}")
print(f"Home Planet:  {home_planet}")
print(f"Primary Diet:   {diet}")
print()
print(f"Scientific Designation: {home_planet}-{creature_name}-{discovery_year}")
print(f"{'='*40}")